# Generated by Django 5.2.4 on 2026-07-28 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='officerprofile',
            name='officer_jurisdiction_matches_level',
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='managed_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sector_officers', to='users.sector'),
        ),
        migrations.AlterField(
            model_name='officerprofile',
            name='level',
            field=models.CharField(choices=[('national', 'National'), ('district', 'District'), ('sector', 'Sector'), ('cell', 'Cell')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.CharField(choices=[('citizen', 'Citizen / Farmer'), ('national_admin', 'National Admin'), ('district_officer', 'District Officer'), ('sector_officer', 'Sector Officer'), ('cell_officer', 'Cell Officer')], default='citizen', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='officerprofile',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('level', 'national'), ('managed_cell__isnull', True), ('managed_district__isnull', True), ('managed_sector__isnull', True)), models.Q(('level', 'district'), ('managed_cell__isnull', True), ('managed_district__isnull', False), ('managed_sector__isnull', True)), models.Q(('level', 'sector'), ('managed_cell__isnull', True), ('managed_sector__isnull', False)), models.Q(('level', 'cell'), ('managed_cell__isnull', False)), _connector='OR'), name='officer_jurisdiction_matches_level'),
        ),
    ]
