# Generated by Django 5.2.4 on 2026-07-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_conversation_message_messageattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='source',
            field=models.CharField(choices=[('app', 'App'), ('ussd', 'USSD')], default='app', max_length=10),
        ),
    ]
