# Generated by Django 5.2.4 on 2026-07-28 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestreport',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvest_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='land',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lands', to='users.cell'),
        ),
        migrations.AddField(
            model_name='land',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='land',
            name='planted_crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lands', to='production.crop'),
        ),
        migrations.AddField(
            model_name='harvestreport',
            name='land',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_reports', to='production.land'),
        ),
        migrations.AddField(
            model_name='livestocklocation',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livestock_locations', to='users.cell'),
        ),
        migrations.AddField(
            model_name='livestocklocation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestock_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livestockproduction',
            name='livestock_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_reports', to='production.livestocklocation'),
        ),
        migrations.AddField(
            model_name='livestockproduction',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livestock_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livestocklocation',
            name='livestock_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='production.livestocktype'),
        ),
        migrations.AddIndex(
            model_name='harvestreport',
            index=models.Index(fields=['crop', 'season', 'season_year'], name='production__crop_id_99a216_idx'),
        ),
        migrations.AddIndex(
            model_name='livestockproduction',
            index=models.Index(fields=['livestock_location', 'season', 'season_year'], name='production__livesto_042dce_idx'),
        ),
    ]
