# Generated by Django 5.2.4 on 2026-07-28 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_resourcerequest'),
        ('users', '0004_alter_user_user_level_buyerprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_available_kg', models.DecimalField(decimal_places=2, max_digits=14)),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_listings', to=settings.AUTH_USER_MODEL)),
                ('harvest_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='production.harvestreport')),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='users.cell')),
            ],
        ),
        migrations.CreateModel(
            name='StorageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('stored', 'Stored'), ('rejected', 'Rejected')], default='requested', max_length=20)),
                ('decision_comment', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('stored_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_requests', to=settings.AUTH_USER_MODEL)),
                ('harvest_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_requests', to='production.harvestreport')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_requests', to='production.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_capacity_kg', models.DecimalField(decimal_places=2, max_digits=14)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_capacities', to='production.crop')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to='production.warehouse')),
            ],
            options={
                'unique_together': {('warehouse', 'crop')},
            },
        ),
    ]
