# Generated by Django 5.2.4 on 2026-07-28 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0002_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerissue',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmerissue',
            name='land',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='production.land'),
        ),
        migrations.AddField(
            model_name='farmerissue',
            name='livestock_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='production.livestocklocation'),
        ),
        migrations.AddField(
            model_name='farmerissue',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues_reported', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmerissue',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='farmerissue',
            index=models.Index(fields=['status', 'category'], name='reports_far_status_fd652c_idx'),
        ),
        migrations.AddConstraint(
            model_name='farmerissue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category', 'crop'), ('land__isnull', False), ('livestock_location__isnull', True)), models.Q(('category', 'livestock'), ('land__isnull', True), ('livestock_location__isnull', False)), _connector='OR'), name='issue_target_matches_category'),
        ),
    ]
