# Generated by Django 5.2.4 on 2026-07-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(choices=[('crop_diagnosis', 'Crop disease diagnosis'), ('livestock_query', 'Livestock query'), ('general_qa', 'General farming Q&A'), ('insight_generation', 'Aggregate insight generation')], max_length=30)),
                ('model_used', models.CharField(max_length=100)),
                ('input_text', models.TextField(blank=True)),
                ('input_image', models.ImageField(blank=True, null=True, upload_to='ai_queries/%Y/%m/')),
                ('response_text', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('was_escalated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
