# Generated by Django 5.2.4 on 2026-07-28 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquerylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aiquerylog',
            index=models.Index(fields=['query_type', 'created_at'], name='ai_aiqueryl_query_t_c56af9_idx'),
        ),
    ]
