# Generated by Django 5.2.4 on 2026-07-28 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_alter_aiquerylog_input_image'),
        ('users', '0004_alter_user_user_level_buyerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('national', 'National'), ('district', 'District')], max_length=20)),
                ('summary_date', models.DateField()),
                ('content', models.TextField()),
                ('model_used', models.CharField(max_length=100)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='users.district')),
            ],
            options={
                'ordering': ['-summary_date'],
                'unique_together': {('scope', 'district', 'summary_date')},
            },
        ),
    ]
