# Generated by Django 5.2.4 on 2026-07-28 11:55

import ai.media_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_insight'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquerylog',
            name='input_audio',
            field=models.FileField(blank=True, null=True, upload_to=ai.media_paths.ai_query_audio_upload_to),
        ),
        migrations.AlterField(
            model_name='aiquerylog',
            name='query_type',
            field=models.CharField(choices=[('crop_diagnosis', 'Crop disease diagnosis'), ('livestock_query', 'Livestock query'), ('general_qa', 'General farming Q&A'), ('insight_generation', 'Aggregate insight generation'), ('voice_message', 'Voice message')], max_length=30),
        ),
    ]
