# Generated by Django 5.2.4 on 2026-07-28 09:20

import ai.media_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiquerylog',
            name='input_image',
            field=models.ImageField(blank=True, null=True, upload_to=ai.media_paths.ai_query_image_upload_to),
        ),
    ]
