# Generated by Django 5.2.4 on 2026-07-28 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('local_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('fertilizer_type', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi', models.CharField(max_length=50, unique=True)),
                ('hectares', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('season', models.CharField(blank=True, choices=[('A', 'Season A'), ('B', 'Season B'), ('C', 'Season C')], max_length=1, null=True)),
                ('season_year', models.PositiveIntegerField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LivestockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LivestockProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=50)),
                ('season', models.CharField(choices=[('A', 'Season A'), ('B', 'Season B'), ('C', 'Season C')], max_length=1)),
                ('season_year', models.PositiveIntegerField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('source', models.CharField(choices=[('farmer_reported', 'Farmer reported'), ('nisr_import', 'NISR import'), ('government_import', 'Other government/institutional import')], default='farmer_reported', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LivestockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('local_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HarvestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('A', 'Season A'), ('B', 'Season B'), ('C', 'Season C')], max_length=1)),
                ('season_year', models.PositiveIntegerField()),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(choices=[('farmer_reported', 'Farmer reported'), ('nisr_import', 'NISR import'), ('government_import', 'Other government/institutional import')], default='farmer_reported', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='harvest_reports', to='production.crop')),
            ],
        ),
    ]
