# Generated by Django 5.2.4 on 2026-07-28 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_harvestlisting_warehouse_storagerequest_and_more'),
        ('users', '0004_alter_user_user_level_buyerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellClimateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_24h_forecast', models.JSONField(blank=True, null=True)),
                ('forecast_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('past_3_months_data', models.JSONField(blank=True, null=True)),
                ('historical_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('cell', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='climate_data', to='users.cell')),
            ],
        ),
    ]
