# Generated by Django 5.2.4 on 2026-07-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_officerprofile_officer_jurisdiction_matches_level_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='officerprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('managed_cell__isnull', False)), fields=('managed_cell', 'specialization'), name='one_active_officer_per_cell_specialization'),
        ),
    ]
