# Generated by Django 5.2.4 on 2026-07-28 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_officerprofile_one_active_officer_per_cell_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.CharField(choices=[('citizen', 'Citizen / Farmer'), ('national_admin', 'National Admin'), ('district_officer', 'District Officer'), ('sector_officer', 'Sector Officer'), ('cell_officer', 'Cell Officer'), ('buyer', 'Produce Buyer')], default='citizen', max_length=20),
        ),
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=150)),
                ('payment_method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank', 'Bank Transfer'), ('cash', 'Cash')], default='mobile_money', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_cells', models.ManyToManyField(blank=True, related_name='buyers', to='users.cell')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_verified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
